name: ci
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  # Build job
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.22"
          check-latest: true

      - name: Download and generate files
        run: |
          go install github.com/kubepug/kubepug/generator@main
          cd generate
          go get -u k8s.io/api@latest
          go mod tidy
          generator k8s.io/api/./.../ -v 9 > ../docs/data/data.json

      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install -r docs/requirements.txt
      - run: python docs/generate_table_md.py
      - run: mkdocs build
